[auth.jwk]
secret = "704125da3b22dcb69a5f846c2d96da45ca21c21fb7e7dd51295f1cff12244e5c"

[server]
port = 3000

[db.sqlite]
path = "./test.db"

[storage.s3]
url = "minio:s3cretMinio@localhost:9000"
bucket = "uploads"

[environment]
god_mode = true
