services:
  4stroblog:
    build: .
    restart: always
    container_name: 4stroblog
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "./site/views:/app/site/views"
      - "./site/uploads:/app/site/uploads"
      - "./site/config:/app/site/config"
