version: '3'

tasks:
  dev:
    desc: "Execute application and theme building"
    deps:
      - start:dev
      - theme:build:watch

  install:
    desc: "Install dependencies across packages"
    cmds:
      - go-task -d ./packages/theme install
      - go-task -d ./packages/site install

  build:
    desc: "Build application"
    dir: './packages/site'
    cmd: go build -o ./bin/server ./cmd 
    env:
      CGO_ENABLED: 1

  start:
    desc: "Start application"
    dir: './packages/site'
    cmd: go run ./cmd

  start:dev:
    desc: "Execute application with live reloading"
    dotenv: ['.dev.env']
    dir: './packages/site'
    cmd: arelo -p '**/*.go' -p 'views/**/*' -p 'config/**/*' -i '**/*_test.go' -- go run ./cmd

  theme:build:
    desc: "Build theme"
    dir: './packages/theme'
    cmd: pnpm build

  theme:build:watch:
    desc: "Build theme in watch mode"
    dir: './packages/theme'
    cmd: pnpm build:watch

  docker:start:
    desc: "Start docker image"
    dir: './infrastructure'
    cmd: docker compose up

  docker:init:
    desc: "Start infra containers"
    dir: './infrastructure'
    cmds:
     - docker compose up rustfs_perms object_storage -d
