services:
  rustfs_perms:
      image: alpine
      user: root
      volumes:
        - ./data:/fix_path
      command: chown -R 10001:10001 /fix_path

  object_storage:
    image: rustfs/rustfs:1.0.0
    restart: always
    container_name: rustfs
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: minio
      RUSTFS_SECRET_KEY: s3cretMinio
    volumes:
      - ./data:/data
      - ./minio/minio.license:/minio.license:ro
    command: server /data --console-address ":9001"

  4stroblog:
    build:
      context: ../
      dockerfile: ./packages/Dockerfile
    restart: always
    container_name: 4stroblog
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "./site/views:/app/site/views"
      - "./site/uploads:/app/site/uploads"
      - "./site/config:/app/site/config"
